New Member
BVPMOSC/Members pull request #43
Opened 2019-04-03 18:18 UTC by akannshu

2019-04-04 04:58 UTC, jainaman224 requested changes

2019-04-04 04:58 UTC, jainaman224 commented on Members.md
> +#### AKanshu Raj
I think i should be `Akanshu` instead of `AKanshu`.

2019-04-13 18:27 UTC, akannshu commented
its Akanshu only

2019-04-14 10:39 UTC, jainaman224 commented
Change ~AKanshu~ to **Akanshu**.
Look closely at `k`.

2019-04-14 10:44 UTC, akannshu commented
done

2019-04-14 11:09 UTC, jainaman224 approved these changes

2019-04-14 11:09 UTC, merged